# enable mouse support
set -g mouse on

# vim mode
set-window-option -g mode-keys vi

# # Set the prefix to Ctrl-a (instead of Ctrl-b)
# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

# Start window numbering at 1
set -g base-index 1

# Start pane numbering at 1
setw -g pane-base-index 1

# Improve colors
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable italic support
set -as terminal-overrides ',*:sitm=\E[3m'

# Enable bold support
set -as terminal-overrides ',*:bold=\E[1m'

# Ensure undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'

# Set scrollback buffer to 10000
set -g history-limit 10000

# Customize the status line
set -g status-fg  green
set -g status-bg  black


# Reload config file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Switch panes using Alt-arrow without prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Set color conf for lazyvim - 

set-option -a terminal-features 'xterm-256color'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'Morantron/tmux-fingers'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

bind-key -n M-c run -b "#{@fingers-cli} start #{pane_id}"
