tap "abue-ammar/tinycast"

brew "bash"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "tmux"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "gh"
brew "lazygit"
brew "mise"
brew "bob"
brew "uv"
brew "powerlevel10k"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "ghostty"
cask "font-jetbrains-mono-nerd-font"
cask "abue-ammar/tinycast/tinycast"
